version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mongo
      - mqtt
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MQTT_BROKER=mqtt
    ports:
      - "8000:8000"

  webui:
    build: ./webui
    container_name: webui
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    ports:
      - "8080:8080"

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  mongo_data:
